import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export class RootLayout extends React.Component<{
  children: React.ReactNode;
}> {
  render() {
    const { children } = this.props;
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  }
}

